### PR TITLE
Move the fetch and convert functions in the background script

### LINKED ISSUE #315: Avoid unnecessary reloading of the document
I see that the extension attempts to reload the document on numerous occasions where reloading isn't warranted. I have the auto-reload setting disabled for both remote and local files, but even then the extension attempts to reload the document on several occasions, here are the two occasions which are prominent:

1. On clicking a section from ToC
2. Activating the tab after a bit of time

I do not see a reason why the document needs to be reloaded in these cases. Normally I would have just ignored this sort of bug if it wasn't causing any disruption, but in this case it triggers another bug which totally wipes the document.

After updating Chromium to version 80, it has started blocking requests to local files due to CORS:
```
Access to XMLHttpRequest at 'file:///tmp/foo.adoc?_=1581403964282' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
```
(This can be easily reproduced by disabling and enabling rendering of the document, which forces the extension to refetch the source text for some reason)

So TL;DR, due to Chrome's new CORS policy, whenever the source text is reloaded via a `XMLHttpRequest`, it is blocked and therefore rendering a blank page, and this happens frequently even with auto-reload turned off.

Please fix it as soon as possible.

### PR DESCRIPTION
**Pull request by Mogztter**
- Refactor extension : Move the fetch and convert functions in the background script
- Refactor tests: Use Puppeteer + Mocha + Chai + Sinon (instead of Karma + Jasmine)

resolves #315 and #316

### CODE REVIEW

**Comment by Mogztter** [comment]
@TheDcoder @sindzicat To workaround the Chrome new security constraint I had to do a pretty large refactoring. 
It would be very keen if you could install this version and do some testing. If you are interested, I can package the extension and publish a "pre-release" version on GitHub. Thanks!

**Comment by sindzicat** [comment]
Yes, of course! I'm ready! ^_^

**Comment by sindzicat** [comment]
Where?

**Comment by Mogztter** [comment]
Here's the link: https://github.com/asciidoctor/asciidoctor-browser-extension/releases/tag/v2.4.0-rc.1

**Comment by sindzicat** [comment]
Works fine! There are only 2 messages in chrome console:
image
But they aren't about our problems.

**Comment by sindzicat** [comment]
Documents updates automatically.

**Comment by sindzicat** [comment]
image

**Comment by sindzicat** [comment]
I found one very strange error.
This code
```
stem:[\sum_{n=0}^\infty F_z].
```
produces the following:
image

I tried demo `$ \sum_{n=0}^\infty F_z` on [mathjax.org](https://mathjax.org) &mdash; all works fine.

image

**Comment by sindzicat** [comment]
There is a new message from mathjax.

image

**Comment by sindzicat** [comment]
It seems to me that something prevents mathjax to work properly. Other things seems to work fine.

**Comment by sindzicat** [comment]
Also, there is one old "problem": after I had typed smth. in my file, saved it and web page has been updated automatically, I see many `<script>` tags with id `asciidoctor-mathjax-config` and `asciidoctor-mathjax-initialization`. But this don't case any errors on rendered document.

image

**Comment by sindzicat** [comment]
I found solution! This is a bug of Mathjax itself.
I downloaded [Mathjax 3.0.1](https://github.com/mathjax/MathJax/releases/tag/3.0.1) and placed its files in your extenstion folder. After updating all works fine!

image

**Comment by sindzicat** [comment]
Now it seems to me you only need to update Mathjax, and extension is production-ready. ^_^

**Comment by sindzicat** [comment]
Is this possible to generate Asciidoctor user manual with `asciidoctor` console command? I'd like to get [this](https://asciidoctor.org/docs/user-manual/) as `.adoc` file and test with new extenstion.

**Comment by Mogztter** [comment]
Thanks for your feedback.
I will try to address the remaining issues tomorrow.

I guess you can clone https://github.com/asciidoctor/asciidoctor.org/tree/master/docs
The User Manual is using a lot of includes so you will need to get the `_includes` directory.

**Comment by Mogztter** [comment]
Did you reload or enable/disable the extension to get the error "The message port closed before a response" ?
I also get this error but we should probably ignore/catch it because most of the time it's safe.

**Comment by sindzicat** [comment]
I'm testing extension on other computer now. I don't have any errors about closed port.

**Comment by TheDcoder** [comment]
Thanks for fixing the XHR issue, I tested the release candidate and it no longer gives me any errors related to CORS.

**Pull request merged**
