### PR TITLE
✨ Add a PlantUML extension

### LINKED ISSUE #160: [Feature Request] Cater for plantuml content in asciidoctor file
Like many others, I too rely on this fantastic tool regularly, to preview my asciidoctor content as I'm developing it. 

My documents often contain plantuml content and it would be great if the diagrams appeared rendered correctly.

### PR DESCRIPTION
**Pull request by Mogztter**
Code taken from https://github.com/pepri/plantuml-viewer and https://github.com/eshepelyuk/asciidoctor-plantuml.js

I'm not sure how we can use the same code base or even if we should do it.
By definition, features in a browser environment will be limited/constrained. Basically we can't access the file system, so I've removed the "fetch and write on disk" feature and I'm using only `rawdeflate.js` and a few functions to encode the text.

@eshepelyuk Let me know what you think :wink: 

 - [x] Use version 0.8.1 of Asciidoctor plantuml.js (and remove `rawdeflate.js`)

Ref #79
Resolves #160

### CODE REVIEW

**Comment by mojavelinux** [comment]
I think we should try as much as possible to reuse so we don't end up having to maintain in two places. That just means finding the right extension/override points in the extension. For example, the PlantUML extension will have to work on a virtual / in-memory file catalog anyway to work with Antora. If we can agree on at least the most basic object API for registering an in-memory file, then we can reuse the extension in both contexts.

**Comment by eshepelyuk** [comment]
I like the idea of having a single PlantUML extension for AsciiDoctor.JS. 

The `plantuml-encoder` library claims to be working in browser too, so the only thing is to disable file generation in browser. The rest of the code could be reused.

**Comment by Mogztter** [comment]
Ok in this case I will open a pull request in the `asciidoctor-plantuml.js` repository to create a browser compatible version.

**Comment by Mogztter** [comment]
https://github.com/eshepelyuk/asciidoctor-plantuml.js can now be used in a browser! 🎉

**Comment by Mogztter** [comment]
I think we are good to go!

@mojavelinux @eshepelyuk Does this look good to you ?

**Comment by mojavelinux** [comment]
This looks great!

**Pull request merged**
