### PR TITLE
🐛 Resolves #240, set the document directory

### LINKED ISSUE #240: Unresolved directive in <stdin> - include::
My main.adoc and ch1.adoc are in the same file.

```

include::ch1.adoc[]

== Attributes

.Built-in
asciidoctor-version:: {asciidoctor-version}
safe-mode-name:: {safe-mode-name}
docdir:: {docdir}
```
adocinclude_failure

This works fine with asciidoctor and asciidoctor-pdf.
similar to https://github.com/asciidoctor/asciidoctor-firefox-addon/issues/21

### PR DESCRIPTION
**Pull request by Mogztter**
Otherwise Firefox cannot resolve include directive with relative path.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Actually, what we agreed on is that Asciidoctor.js would set the docdir attribute, not the base_dir option.

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/document.rb#L394-L401

If you set the docdir attribute, it's left as is. Then it should work.

**Comment by mojavelinux** [comment]
(that's how you are able to use a file URI as the base_dir).

**Comment by Mogztter** [comment]
Indeed, I forgot about that 😳
On the same topic do you still think it makes sense to define the `base_dir` ?

https://github.com/asciidoctor/asciidoctor-browser-extension/issues/68

**Comment by mojavelinux** [comment]
Nope, there's no reason to define base_dir anymore. In fact, it probably hurts more than it helps.

**Comment by Mogztter** [comment]
@mojavelinux Since `docdir` is an attribute, a user could define it. Do you think we should override the value no matter what or should we set the docdir only when the attribute is not define ?

**Comment by mojavelinux** [comment]
Yes, docdir should be overridden by the extension. This is a not a configurable attribute.

**Comment by Mogztter** [comment]
Alright then I think we are good to go.

**Pull request merged**
