### PR TITLE
Resolves #209, use highlightjs as source-highlighter

### LINKED ISSUE #209: Too much padding in highlighted source code block
There's too much padding in the container surrounding a highlighted source code block. The problem is that the `<pre>` element is missing the class `highlightjs`, which activates additional styles from the default stylesheet to tighten the spacing.

Using the browser extension:

```html
<div class="listingblock">
<div class="content">
<pre class="highlight"><code class="language-js hljs javascript" data-lang="js">...</code></pre>
</div>
</div>
```

Using the asciidoctor command:

```html
<div class="listingblock">
<div class="content">
<pre class="highlightjs highlight"><code class="language-js hljs javascript" data-lang="js">...</code></pre>
</div>
</div>
```

### PR DESCRIPTION
**Pull request by Mogztter**
Resolves #209

### CODE REVIEW

**Comment by mojavelinux** [comment]
I don't think we should force the use of the source highlighter. Instead, I think we should detect that the `source-highlighter` attribute is set, then force set it to `highlight.js`. This should eliminate complaints as well when someone uses a different source highlighter while still being consistent w/ the behavior of core.

Of course, if users want to enable it by default, they can set it in the default attributes on the settings page. But we still always force the value to highlight.js for now.

(Unless like docgist you want to also support prettier, in which case we'd just need to preserve that value)

**Comment by Mogztter** [comment]
> I don't think we should force the use of the source highlighter. 

Why is that ? I should mention that we are running Highlight.js regardless of the `source-highlighter` attribute: https://github.com/asciidoctor/asciidoctor-browser-extension/blob/f4961737a468ff1d485c5a8db7db29872700ad1e/app/js/renderer.js#L276

> Instead, I think we should detect that the source-highlighter attribute is set, then force set it to highlight.js. 
> This should eliminate complaints as well when someone uses a different source highlighter while still being consistent w/ the behavior of core.

I don't understand how it eliminate complaints ? We are still forcing the source highlighter to Highlight.js. If I understand correctly, the only difference would be that we only force the value if the `source-highlighter` attribute is defined ?

> Of course, if users want to enable it by default, they can set it in the default attributes on the settings page. But we still always force the value to highlight.js for now.

We should probably don't run Highlight.js otherwise the padding will be wrong if the user does not define the `source-highlighter` attribute.

> (Unless like docgist you want to also support prettier, in which case we'd just need to preserve that value)

Why not, I will need to have a look at Docgist code.

**Comment by mojavelinux** [comment]
> Why is that ?

Really just to be consistent with core. But I've had documents where the syntax highlighting not helping and I prefer it not to be enabled.

> I should mention that we are running Highlight.js regardless of the source-highlighter attribute:

Like docgist, I think we should activate this behavior based on the use of the source-highlighter attribute.

> I don't understand how it eliminate complaints ?

What I mean here is that someone tries to use pygments or rouge and it doesn't work. We just interpret that hint as "enable source highlighting" and the user doesn't know the details of how we made it work.

**Comment by Mogztter** [comment]
Alright, I get it now 😄
I will update my pull request accordingly.

**Comment by mojavelinux** [comment]
\o/

**Comment by Mogztter** [comment]
@mojavelinux It should be OK, could you please review it again ?

**Comment by mojavelinux** [comment]
This looks good so far. Two small changes.

* (if possible) Don't append the highlight.js script to the page if we're not going to use it
* Use the value `highlight.js` instead of `highlightjs` (as we're trying to standardize it)

**Comment by Mogztter** [comment]
@mojavelinux Done!

While working on it, I've also fixed a few issues (but I'm willing to move them to dedicated pull requests):

* Remove a debug `console.log`
* Add `asciidoctor-browser-` prefix to `id` (to avoid collision)
* Only append highlight stylesheet once
* Update a test to make sure that the default stylesheet is added to the DOM (`css/themes/asciidoctor.css`)

**Comment by mojavelinux** [comment]
Looks great!

**Pull request merged**
